export const cuisineTypes = ["korean", "french", "gastronomique"]
export const lieuTypes = ["Restaurants", "Museum", "Bars", "Parcs"]
export const avgPrice = ["1", "2", "3", "4", "5"]
export const stars = ["1", "2", "3"]
export const art = ["realism", "cubism", "street-art"]
export const artType = ["Sculpture", "Peinture", "Objets"]
export const barTypes = ["bar à vin", "bar à cocktails", "pub"]
export const parcTypes = ["parc floral", "parc forestier"]